package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fmt"
	"time"

	"github.com/ludovicplt/muscubackend/auth"
	"github.com/ludovicplt/muscubackend/graph/model"
	"github.com/ludovicplt/muscubackend/utils"
)

// CreateUser is the resolver for the CreateUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, user model.CreateUserInput) (*model.ConnectionAccepted, error) {
	var existingUser model.User
	result := r.DB.Where("email = ?", user.Email).First(&existingUser)
	if result.Error == nil {
		return nil, fmt.Errorf("user with email already exists")
	}

	hashedPassword, err := auth.HashPassword(user.Password)
	if err != nil {
		return nil, fmt.Errorf("failed to hash password: %v", err)
	}

	newUser := model.User{
		Name:      user.Name,
		Email:     user.Email,
		Password:  hashedPassword,
		Age:       user.Age,
		CreatedAt: utils.TimeToString(time.Now()),
	}

	creationResult := r.DB.Create(&newUser)
	if creationResult.Error != nil {
		return nil, result.Error
	}

	tokenstring, err := auth.GenerateJWT(newUser.ID, newUser.Email, time.Hour*72)
	if err != nil {
		return nil, fmt.Errorf("failed to generate token: %v", err)
	}

	return &model.ConnectionAccepted{
		Token: tokenstring,
	}, nil
}

// LoginUser is the resolver for the LoginUser field.
func (r *mutationResolver) LoginUser(ctx context.Context, user model.LoginUserInput) (*model.ConnectionAccepted, error) {
	var existingUser model.User
	result := r.DB.Where("email = ?", user.Email).First(&existingUser)
	if result.Error != nil {
		return nil, fmt.Errorf("user with email does not exist")
	}

	if pass_result, _ := auth.ComparePasswordAndHash(user.Password, existingUser.Password); !pass_result {
		return nil, fmt.Errorf("invalid password")
	}

	tokenstring, err := auth.GenerateJWT(existingUser.ID, existingUser.Email, time.Hour*72)
	if err != nil {
		return nil, fmt.Errorf("failed to generate token: %v", err)
	}

	return &model.ConnectionAccepted{
		Token: tokenstring,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
