// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ConnectionAccepted struct {
	Token string `json:"Token"`
}

type CreateMachineInput struct {
	Name string `json:"Name"`
}

type CreateUserInput struct {
	Name     string `json:"Name"`
	Password string `json:"Password"`
	Age      int32  `json:"Age"`
	Email    string `json:"Email"`
}

type Exercise struct {
	ID        string  `json:"ID"`
	Name      string  `json:"Name"`
	CreatedAt string  `json:"CreatedAt"`
	UpdatedAt *string `json:"UpdatedAt,omitempty"`
	Image     *string `json:"Image,omitempty"`
	Tags      []*Tags `json:"Tags"`
}

type LoginUserInput struct {
	Email    string `json:"Email"`
	Password string `json:"Password"`
}

type Machine struct {
	ID        string  `json:"ID"`
	Name      string  `json:"Name"`
	Image     *string `json:"Image,omitempty"`
	CreatedAt *string `json:"CreatedAt,omitempty"`
	UpdatedAt *string `json:"UpdatedAt,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type Tags struct {
	ID   string `json:"ID"`
	Name string `json:"Name"`
}

type TokenTable struct {
	ID    uint   `json:"ID"`
	Token string `json:"token"`
}

type User struct {
	ID        uint    `json:"ID"`
	Name      string  `json:"Name"`
	Email     string  `json:"Email"`
	Password  string  `json:"Password"`
	Age       int32   `json:"Age"`
	CreatedAt string  `json:"CreatedAt"`
	UpdatedAt *string `json:"UpdatedAt,omitempty"`
	DeletedAt *string `json:"DeletedAt,omitempty"`
	Deleted   *bool   `json:"Deleted,omitempty"`
}
